export default [
  { name: 'Buttons', url: 'https://space-pi.com' },
  { name: 'Buttons', url: 'https://space-pi.com' },
  { name: 'Buttons', url: 'https://space-pi.com' },
  { name: 'Buttons', url: 'https://space-pi.com' },
  { name: 'Buttons', url: 'https://space-pi.com' },
  { name: 'Buttons', url: 'https://space-pi.com' },
  { name: 'Buttons', url: 'https://space-pi.com' },
  { name: 'Buttons', url: 'https://space-pi.com' },
  { name: 'Buttons', url: 'https://space-pi.com' },
  { name: 'Buttons', url: 'https://space-pi.com' },
  { name: 'Buttons', url: 'https://space-pi.com' },
  { name: 'Buttons', url: 'https://space-pi.com' },
  { name: 'Buttons', url: 'https://space-pi.com' },
  { name: 'Buttons', url: 'https://space-pi.com' },
  { name: 'Buttons', url: 'https://space-pi.com' },
  { name: 'Buttons', url: 'https://space-pi.com' },
  { name: 'Buttons', url: 'https://space-pi.com' },
  { name: 'Buttons', url: 'https://space-pi.com' }
]
